<?xml version='1.0' encoding='utf-8'?>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>5.6. try Blocks and Exception Handling</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <link href="stylesheet.css" type="text/css" rel="stylesheet"/>
<link href="page_styles.css" type="text/css" rel="stylesheet"/>
</head>
  <body class="calibre">
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr><td><div STYLE="MARGIN-LEFT: 0.15in;"><a href="001-contents.html"><img src="images/teamlib.gif" width="62" height="15" border="0" align="absmiddle"  alt="Team LiB"></a></div></td><td align="right"><div STYLE="MARGIN-LEFT: 0.15in;">
<a href="058-5.5._jump_statements.html"><img src="images/previous.gif" width="62" height="15" border="0" align="absmiddle" alt="Previous Section"></a>
<a href="060-chapter_summary.html"><img src="images/next.gif" width="41" height="15" border="0" align="absmiddle" alt="Next Section"></a></div></td></tr></table><h3 id="filepos1368051" class="calibre29"><span class="bold">5.6. <code class="calibre54"><tt class="calibre54"><span class="calibre55"><span class="calibre2"><tt class="calibre54"><span class="calibre56"><span class="bold">try</span></span></tt></span></span></tt></code> Blocks and Exception Handling</span></h3><div class="calibre12">&#160;</div>
<div class="calibre28"><img alt="Image" src="images/00010.jpg" class="calibre9"/></div>
<p class="calibre14">Exceptions are run-time anomalies&#8212;such as losing a database connection or encountering unexpected input&#8212;that exist outside the normal functioning of a program. Dealing with anomalous behavior can be one of the most difficult parts of designing any system.</p><div class="calibre15">&#160;</div>
<p class="calibre25">Exception handling is generally used when one part of a program detects a problem that it cannot resolve and the problem is such that the detecting part of the program cannot continue. In such cases, the detecting part needs a way to signal that something happened and that it cannot continue. Moreover, the detecting part needs a way to signal the problem without knowing what part of the program will deal with the exceptional condition. Having signaled what happened, the detecting part stops processing.</p><div class="calibre22">&#160;</div>
<p class="calibre25">A program that contains code that might raise an exception (usually) has another part to handle whatever happened. For example, if the problem is invalid input, the handling part might ask the user to provide correct input. If the database was lost, the handling part might alert an operator.</p><div class="calibre22">&#160;</div>
<p class="calibre25">Exception handling supports this cooperation between the detecting and handling parts of a program. In C++, exception handling involves</p><div class="calibre22">&#160;</div>
<blockquote class="calibre26"><p class="calibre27">&#8226; <a id="filepos1369863" href="061-defined_terms.html#filepos1411033"><code class="calibre23"><tt class="calibre23"><span class="calibre24"><span><tt class="calibre23"><span class="calibre32"><span class="calibre5">throw</span></span></tt></span></span></tt></code>
<strong class="calibre5">expressions</strong></a>, which the detecting part uses to indicate that it encountered something it can&#8217;t handle. We say that a <code class="calibre23"><tt class="calibre23"><span class="calibre24">throw</span></tt></code>
<strong class="calibre5"><a id="filepos1370258" href="061-defined_terms.html#filepos1409331">raises</a></strong> an exception.</p></blockquote><div class="calibre15">&#160;</div>
<blockquote class="calibre26"><p class="calibre27">&#8226; <a id="filepos1370430" href="061-defined_terms.html#filepos1411534"><code class="calibre23"><tt class="calibre23"><span class="calibre24"><span><tt class="calibre23"><span class="calibre32"><span class="calibre5">try</span></span></tt></span></span></tt></code>
<strong class="calibre5">blocks</strong></a>, which the handling part uses to deal with an exception. A <code class="calibre23"><tt class="calibre23"><span class="calibre24">try</span></tt></code> block starts with the keyword <code class="calibre23"><tt class="calibre23"><span class="calibre24">try</span></tt></code> and ends with one or more <a id="filepos1370880" href="061-defined_terms.html#filepos1401925"><code class="calibre23"><tt class="calibre23"><span class="calibre24"><span><tt class="calibre23"><span class="calibre32"><span class="calibre5">catch</span></span></tt></span></span></tt></code>
<strong class="calibre5">clauses</strong></a>. Exceptions thrown from code executed inside a <code class="calibre23"><tt class="calibre23"><span class="calibre24">try</span></tt></code> block are usually handled by one of the <code class="calibre23"><tt class="calibre23"><span class="calibre24">catch</span></tt></code> clauses. Because they &#8220;handle&#8221; the exception, <code class="calibre23"><tt class="calibre23"><span class="calibre24">catch</span></tt></code> clauses are also known as <strong class="calibre5"><a id="filepos1371468" href="061-defined_terms.html#filepos1405959">exception handlers</a></strong>.</p></blockquote><div class="calibre15">&#160;</div>
<blockquote class="calibre26"><p class="calibre27">&#8226; A set of <a id="filepos1371648" href="061-defined_terms.html#filepos1405165"><code class="calibre23"><tt class="calibre23"><span class="calibre24"><span><tt class="calibre23"><span class="calibre32"><span class="calibre5">exception</span></span></tt></span></span></tt></code>
<strong class="calibre5">classes</strong></a> that are used to pass information about what happened between a <code class="calibre23"><tt class="calibre23"><span class="calibre24">throw</span></tt></code> and an associated <code class="calibre23"><tt class="calibre23"><span class="calibre24">catch</span></tt></code>.</p></blockquote><div class="calibre15">&#160;</div>
<p class="calibre14">In the remainder of this section, we&#8217;ll introduce these three components of exception handling. We&#8217;ll also have more to say about exceptions in &#167; <a href="171-18.1._exception_handling.html#filepos4855328">18.1</a> (p. <a href="171-18.1._exception_handling.html#filepos4855328">772</a>).</p><div class="calibre15">&#160;</div>
<h4 id="filepos1372413" class="calibre37"><span class="calibre5">5.6.1. A <code class="calibre23"><tt class="calibre23"><span class="calibre24"><span><tt class="calibre23"><span class="calibre32"><span class="calibre5">throw</span></span></tt></span></span></tt></code> Expression</span></h4><div class="calibre38">&#160;</div>
<p class="calibre14">The detecting part of a program uses a <code class="calibre23"><tt class="calibre23"><span class="calibre24">throw</span></tt></code> expression to raise an exception. A <code class="calibre23"><tt class="calibre23"><span class="calibre24">throw</span></tt></code> consists of the keyword <code class="calibre23"><tt class="calibre23"><span class="calibre24">throw</span></tt></code> followed by an expression. The type of the expression determines what kind of exception is thrown. A <code class="calibre23"><tt class="calibre23"><span class="calibre24">throw</span></tt></code> expression is usually followed by a semicolon, making it into an expression statement.</p><div class="calibre15">&#160;</div>
<p class="calibre25"><a id="filepos1373296"/>As a simple example, recall the program in &#167; <a href="015-1.5._introducing_classes.html#filepos237516">1.5.2</a> (p. <a href="015-1.5._introducing_classes.html#filepos237516">23</a>) that added two objects of type <code class="calibre23"><tt class="calibre23"><span class="calibre24">Sales_item</span></tt></code>. That program checked whether the records it read referred to the same book. If not, it printed a message and exited.</p><div class="calibre22">&#160;</div>
<p class="calibre40"><span class="calibre41"><span class="calibre5"/></span></p><div class="calibre38">&#160;</div>
<blockquote class="calibre13"><p class="calibre31"><tt class="calibre23"><span class="calibre24">Sales_item item1, item2;<br class="calibre6"/>cin &gt;&gt; item1 &gt;&gt; item2;<br class="calibre6"/>// <span><span class="calibre45"><span class="calibre16">first check that</span></span></span>
<span><tt class="calibre23"><span class="calibre46"><span class="calibre16">item1</span></span></tt></span>
<span><span class="calibre45"><span class="calibre16">and</span></span></span>
<span><tt class="calibre23"><span class="calibre46"><span class="calibre16">item2</span></span></tt></span>
<span><span class="calibre45"><span class="calibre16">represent the same book</span></span></span><br class="calibre6"/>if (item1.isbn() == item2.isbn()) {<br class="calibre6"/>&#160;&#160;&#160;&#160;cout &lt;&lt; item1 + item2 &lt;&lt; endl;<br class="calibre6"/>&#160;&#160;&#160;&#160;return 0;&#160;&#160;&#160;// <span><span class="calibre45"><span class="calibre16">indicate success</span></span></span><br class="calibre6"/>} else {<br class="calibre6"/>&#160;&#160;&#160;&#160;cerr &lt;&lt; "Data must refer to same ISBN"<br class="calibre6"/>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&lt;&lt; endl;<br class="calibre6"/>&#160;&#160;&#160;&#160;return -1;&#160;&#160;// <span><span class="calibre45"><span class="calibre16">indicate failure</span></span></span><br class="calibre6"/>}</span></tt></p></blockquote><div class="calibre22">&#160;</div>
<p class="calibre25">In a more realistic program, the part that adds the objects might be separated from the part that manages the interaction with a user. In this case, we might rewrite the test to throw an exception rather than returning an error indicator:</p><div class="calibre22">&#160;</div>
<p class="calibre40"><span class="calibre41"><span class="calibre5"/></span></p><div class="calibre38">&#160;</div>
<blockquote class="calibre13"><p class="calibre31"><tt class="calibre23"><span class="calibre24">// <span><span class="calibre45"><span class="calibre16">first check that the data are for the same item</span></span></span><br class="calibre6"/>if (item1.isbn() != item2.isbn())<br class="calibre6"/>&#160;&#160;&#160;&#160;throw runtime_error("Data must refer to same ISBN");<br class="calibre6"/>// <span><span class="calibre45"><span class="calibre16">if we're still here, the</span></span></span>
<span><span class="calibre50">ISBN</span></span><span><span class="calibre45"><span class="calibre16">s are the same</span></span></span><br class="calibre6"/>cout &lt;&lt; item1 + item2 &lt;&lt; endl;</span></tt></p></blockquote><div class="calibre22">&#160;</div>
<p class="calibre14">In this code, if the <small class="calibre48">ISBN</small>s differ, we throw an expression that is an object of type <code class="calibre23"><tt class="calibre23"><span class="calibre24">runtime_error</span></tt></code>. Throwing an exception terminates the current function and transfers control to a handler that will know how to handle this error.</p><div class="calibre15">&#160;</div>
<p class="calibre25">The type <code class="calibre23"><tt class="calibre23"><span class="calibre24">runtime_error</span></tt></code> is one of the standard library exception types and is defined in the <code class="calibre23"><tt class="calibre23"><span class="calibre24">stdexcept</span></tt></code> header. We&#8217;ll have more to say about these types in &#167; <a href="059-5.6._try_blocks_and_exception_handling.html#filepos1391364">5.6.3</a> (p. <a href="059-5.6._try_blocks_and_exception_handling.html#filepos1391364">197</a>). We must initialize a <code class="calibre23"><tt class="calibre23"><span class="calibre24">runtime_error</span></tt></code> by giving it a <code class="calibre23"><tt class="calibre23"><span class="calibre24">string</span></tt></code> or a C-style character string (&#167; <a href="034-3.5._arrays.html#filepos918393">3.5.4</a>, p. <a href="034-3.5._arrays.html#filepos918393">122</a>). That string provides additional information about the problem.</p><div class="calibre22">&#160;</div>
<h4 id="filepos1377241" class="calibre37"><span class="calibre5">5.6.2. The <code class="calibre23"><tt class="calibre23"><span class="calibre24"><span><tt class="calibre23"><span class="calibre32"><span class="calibre5">try</span></span></tt></span></span></tt></code> Block</span></h4><div class="calibre38">&#160;</div>
<p class="calibre14">The general form of a <code class="calibre23"><tt class="calibre23"><span class="calibre24">try</span></tt></code> block is</p><div class="calibre15">&#160;</div>
<p class="calibre40"><span class="calibre41"><span class="calibre5"/></span></p><div class="calibre38">&#160;</div>
<blockquote class="calibre13"><p class="calibre31"><tt class="calibre23"><span class="calibre24">try {<br class="calibre6"/>&#160;&#160;&#160;&#160;<span><span class="calibre45"><span class="calibre16">program-statements</span></span></span><br class="calibre6"/>} catch (<span><span class="calibre45"><span class="calibre16">exception-declaration</span></span></span>) {<br class="calibre6"/>&#160;&#160;&#160;&#160;<span><span class="calibre45"><span class="calibre16">handler-statements</span></span></span><br class="calibre6"/>} catch (<span><span class="calibre45"><span class="calibre16">exception-declaration</span></span></span>) {<br class="calibre6"/>&#160;&#160;&#160;&#160;<span><span class="calibre45"><span class="calibre16">handler-statements</span></span></span><br class="calibre6"/>} // <span><span class="calibre45"><span class="calibre16">. . .</span></span></span></span></tt></p></blockquote><div class="calibre22">&#160;</div>
<p class="calibre14">A <code class="calibre23"><tt class="calibre23"><span class="calibre24">try</span></tt></code> block begins with the keyword <code class="calibre23"><tt class="calibre23"><span class="calibre24">try</span></tt></code> followed by a block, which, as usual, is a sequence of statements enclosed in curly braces.</p><div class="calibre15">&#160;</div>
<p class="calibre25"><a id="filepos1378878"/>Following the <code class="calibre23"><tt class="calibre23"><span class="calibre24">try</span></tt></code> block is a list of one or more <code class="calibre23"><tt class="calibre23"><span class="calibre24">catch</span></tt></code> clauses. A <code class="calibre23"><tt class="calibre23"><span class="calibre24">catch</span></tt></code> consists of three parts: the keyword <code class="calibre23"><tt class="calibre23"><span class="calibre24">catch</span></tt></code>, the declaration of a (possibly unnamed) object within parentheses (referred to as an <strong class="calibre5"><a id="filepos1379347" href="061-defined_terms.html#filepos1405543">exception declaration</a></strong>), and a block. When a <code class="calibre23"><tt class="calibre23"><span class="calibre24">catch</span></tt></code> is selected to handle an exception, the associated block is executed. Once the <code class="calibre23"><tt class="calibre23"><span class="calibre24">catch</span></tt></code> finishes, execution continues with the statement immediately following the last <code class="calibre23"><tt class="calibre23"><span class="calibre24">catch</span></tt></code> clause of the <code class="calibre23"><tt class="calibre23"><span class="calibre24">try</span></tt></code> block.</p><div class="calibre22">&#160;</div>
<p class="calibre25">The <em class="calibre16">program-statements</em> inside the <code class="calibre23"><tt class="calibre23"><span class="calibre24">try</span></tt></code> constitute the normal logic of the program. Like any other blocks, they can contain any C++ statement, including declarations. As with any block, variables declared inside a <code class="calibre23"><tt class="calibre23"><span class="calibre24">try</span></tt></code> block are inaccessible outside the block&#8212;in particular, they are not accessible to the <code class="calibre23"><tt class="calibre23"><span class="calibre24">catch</span></tt></code> clauses.</p><div class="calibre22">&#160;</div>
<h5 class="calibre39"><span class="calibre5">Writing a Handler</span></h5><div class="calibre38">&#160;</div>
<p class="calibre14">In the preceding example, we used a <code class="calibre23"><tt class="calibre23"><span class="calibre24">throw</span></tt></code> to avoid adding two <code class="calibre23"><tt class="calibre23"><span class="calibre24">Sales_item</span></tt></code>s that represented different books. We imagined that the part of the program that added two <code class="calibre23"><tt class="calibre23"><span class="calibre24">Sales_item</span></tt></code>s was separate from the part that communicated with the user. The part that interacts with the user might contain code something like the following to handle the exception that was thrown:</p><div class="calibre15">&#160;</div>
<p class="calibre40"><span class="calibre41"><span class="calibre5"/></span></p><div class="calibre38">&#160;</div>
<blockquote class="calibre13"><p class="calibre31"><tt class="calibre23"><span class="calibre24">while (cin &gt;&gt; item1 &gt;&gt; item2) {<br class="calibre6"/>&#160;&#160;&#160;&#160;try {<br class="calibre6"/>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;// <span><span class="calibre45"><span class="calibre16">execute code that will add the two</span></span></span>
<span><tt class="calibre23"><span class="calibre46"><span class="calibre16">Sales_item</span></span></tt></span><span><span class="calibre45"><span class="calibre16">s</span></span></span><br class="calibre6"/>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;// <span><span class="calibre45"><span class="calibre16">if the addition fails, the code throws a</span></span></span>
<span><tt class="calibre23"><span class="calibre46"><span class="calibre16">runtime_error</span></span></tt></span>
<span><span class="calibre45"><span class="calibre16">exception</span></span></span><br class="calibre6"/>&#160;&#160;&#160;&#160;} catch (runtime_error err) {<br class="calibre6"/>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;// <span><span class="calibre45"><span class="calibre16">remind the user that the</span></span></span>
<span><span class="calibre50">ISBN</span></span><span><span class="calibre45"><span class="calibre16">s must match and prompt for another pair</span></span></span><br class="calibre6"/>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;cout &lt;&lt; err.what()<br class="calibre6"/>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&lt;&lt; "\nTry Again?&#160;&#160;Enter y or n" &lt;&lt; endl;<br class="calibre6"/>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;char c;<br class="calibre6"/>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;cin &gt;&gt; c;<br class="calibre6"/>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;if (!cin || c == 'n')<br class="calibre6"/>&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;break;&#160;&#160;&#160;&#160;&#160;&#160;// <span><span class="calibre45"><span class="calibre16">break out of the</span></span></span>
<span><tt class="calibre23"><span class="calibre46"><span class="calibre16">while</span></span></tt></span>
<span><span class="calibre45"><span class="calibre16">loop</span></span></span><br class="calibre6"/>&#160;&#160;&#160;&#160;}<br class="calibre6"/>}</span></tt></p></blockquote><div class="calibre22">&#160;</div>
<p class="calibre14">The ordinary logic of the program that manages the interaction with the user appears inside the <code class="calibre23"><tt class="calibre23"><span class="calibre24">try</span></tt></code> block. This part of the program is wrapped inside a <code class="calibre23"><tt class="calibre23"><span class="calibre24">try</span></tt></code> because it might throw an exception of type <code class="calibre23"><tt class="calibre23"><span class="calibre24">runtime_error</span></tt></code>.</p><div class="calibre15">&#160;</div>
<p class="calibre25">This <code class="calibre23"><tt class="calibre23"><span class="calibre24">try</span></tt></code> block has a single <code class="calibre23"><tt class="calibre23"><span class="calibre24">catch</span></tt></code> clause, which handles exceptions of type <code class="calibre23"><tt class="calibre23"><span class="calibre24">runtime_error</span></tt></code>. The statements in the block following the <code class="calibre23"><tt class="calibre23"><span class="calibre24">catch</span></tt></code> are executed if code inside the <code class="calibre23"><tt class="calibre23"><span class="calibre24">try</span></tt></code> block throws a <code class="calibre23"><tt class="calibre23"><span class="calibre24">runtime_error</span></tt></code>. Our <code class="calibre23"><tt class="calibre23"><span class="calibre24">catch</span></tt></code> handles the error by printing a message and asking the user to indicate whether to continue. If the user enters &#8217;<code class="calibre23"><tt class="calibre23"><span class="calibre24">n</span></tt></code>&#8217;, then the <code class="calibre23"><tt class="calibre23"><span class="calibre24">break</span></tt></code> is executed and we exit the <code class="calibre23"><tt class="calibre23"><span class="calibre24">while</span></tt></code>. Otherwise, execution falls through to the closing brace of the <code class="calibre23"><tt class="calibre23"><span class="calibre24">while</span></tt></code>, which transfers control back to the <code class="calibre23"><tt class="calibre23"><span class="calibre24">while</span></tt></code> condition for the next iteration.</p><div class="calibre22">&#160;</div>
<p class="calibre25">The prompt to the user prints the return from <code class="calibre23"><tt class="calibre23"><span class="calibre24">err.what()</span></tt></code>. We know that <code class="calibre23"><tt class="calibre23"><span class="calibre24">err</span></tt></code> has type <code class="calibre23"><tt class="calibre23"><span class="calibre24">runtime_error</span></tt></code>, so we can infer that <code class="calibre23"><tt class="calibre23"><span class="calibre24">what</span></tt></code> is a member function (&#167; <a href="015-1.5._introducing_classes.html#filepos237516">1.5.2</a>, p. <a href="015-1.5._introducing_classes.html#filepos237516">23</a>) of the <code class="calibre23"><tt class="calibre23"><span class="calibre24">runtime_error</span></tt></code> class. Each of the library exception classes defines a member function named <code class="calibre23"><tt class="calibre23"><span class="calibre24">what</span></tt></code>. These functions take no arguments and return a C-style character string (i.e., a <code class="calibre23"><tt class="calibre23"><span class="calibre24">const char*</span></tt></code>). The <code class="calibre23"><tt class="calibre23"><span class="calibre24">what</span></tt></code> member of <a id="filepos1386153"/><code class="calibre23"><tt class="calibre23"><span class="calibre24">runtime_error</span></tt></code> returns a copy of the <code class="calibre23"><tt class="calibre23"><span class="calibre24">string</span></tt></code> used to initialize the particular object. If the code described in the previous section threw an exception, then this <code class="calibre23"><tt class="calibre23"><span class="calibre24">catch</span></tt></code> would print</p><div class="calibre22">&#160;</div>
<blockquote class="calibre13"><p class="calibre31"><tt class="calibre23"><span class="calibre24"><span><tt class="calibre23"><span class="calibre32"><span class="calibre5">Data must refer to same <small class="calibre48">ISBN</small></span></span></tt></span><br class="calibre6"/><span><tt class="calibre23"><span class="calibre32"><span class="calibre5">Try Again?&#160;&#160;Enter y or n</span></span></tt></span></span></tt></p></blockquote><div class="calibre22">&#160;</div>
<h5 class="calibre39"><span class="calibre5">Functions Are Exited during the Search for a Handler</span></h5><div class="calibre38">&#160;</div>
<p class="calibre14">In complicated systems, the execution path of a program may pass through multiple <code class="calibre23"><tt class="calibre23"><span class="calibre24">try</span></tt></code> blocks before encountering code that throws an exception. For example, a <code class="calibre23"><tt class="calibre23"><span class="calibre24">try</span></tt></code> block might call a function that contains a <code class="calibre23"><tt class="calibre23"><span class="calibre24">try</span></tt></code>, which calls another function with its own <code class="calibre23"><tt class="calibre23"><span class="calibre24">try</span></tt></code>, and so on.</p><div class="calibre15">&#160;</div>
<p class="calibre25">The search for a handler reverses the call chain. When an exception is thrown, the function that threw the exception is searched first. If no matching <code class="calibre23"><tt class="calibre23"><span class="calibre24">catch</span></tt></code> is found, that function terminates. The function that called the one that threw is searched next. If no handler is found, that function also exits. That function&#8217;s caller is searched next, and so on back up the execution path until a <code class="calibre23"><tt class="calibre23"><span class="calibre24">catch</span></tt></code> of an appropriate type is found.</p><div class="calibre22">&#160;</div>
<p class="calibre25">If no appropriate <code class="calibre23"><tt class="calibre23"><span class="calibre24">catch</span></tt></code> is found, execution is transferred to a library function named <code class="calibre23"><tt class="calibre23"><span class="calibre24"><span><tt class="calibre23"><span class="calibre32"><span class="calibre5"><a id="filepos1388508" href="061-defined_terms.html#filepos1410706">terminate</a></span></span></tt></span></span></tt></code>. The behavior of that function is system dependent but is guaranteed to stop further execution of the program.</p><div class="calibre22">&#160;</div>
<p class="calibre25">Exceptions that occur in programs that do not define any <code class="calibre23"><tt class="calibre23"><span class="calibre24">try</span></tt></code> blocks are handled in the same manner: After all, if there are no <code class="calibre23"><tt class="calibre23"><span class="calibre24">try</span></tt></code> blocks, there can be no handlers. If a program has no <code class="calibre23"><tt class="calibre23"><span class="calibre24">try</span></tt></code> blocks and an exception occurs, then <code class="calibre23"><tt class="calibre23"><span class="calibre24">terminate</span></tt></code> is called and the program is exited.</p><div class="calibre22">&#160;</div>
<div class="calibre35"><blockquote class="calibre26"><hr class="calibre34"/><blockquote class="calibre13"><p class="calibre14"><span class="calibre5"><a/>Caution: Writing Exception Safe Code is <em class="calibre16">Hard</em></span></p></blockquote><div class="calibre15">&#160;</div>
<blockquote class="calibre13"><p class="calibre14">It is important to realize that exceptions interrupt the normal flow of a program. At the point where the exception occurs, some of the computations that the caller requested may have been done, while others remain undone. In general, bypassing part of the program might mean that an object is left in an invalid or incomplete state, or that a resource is not freed, and so on. Programs that properly &#8220;clean up&#8221; during exception handling are said to be <em class="calibre16"><a id="filepos1390090" href="061-defined_terms.html#filepos1406300">exception safe.</a></em> Writing exception safe code is surprisingly hard, and (largely) beyond the scope of this language Primer.</p></blockquote><div class="calibre15">&#160;</div>
<blockquote class="calibre36"><p class="calibre25">Some programs use exceptions simply to terminate the program when an exceptional condition occurs. Such programs generally don&#8217;t worry about exception safety.</p></blockquote><div class="calibre22">&#160;</div>
<blockquote class="calibre36"><p class="calibre25">Programs that do handle exceptions and continue processing generally must be constantly aware of whether an exception might occur and what the program must do to ensure that objects are valid, that resources don&#8217;t leak, and that the program is restored to an appropriate state.</p></blockquote><div class="calibre22">&#160;</div>
<blockquote class="calibre36"><p class="calibre25">We will occasionally point out particularly common techniques used to promote exception safety. However, readers whose programs require robust exception handling should be aware that the techniques we cover are insufficient by themselves to achieve exception safety.</p></blockquote><div class="calibre22">&#160;</div>
<hr class="calibre34"/></blockquote></div><div class="calibre3">&#160;</div>
<h4 id="filepos1391364" class="calibre37"><span class="calibre5"><a id="filepos1391397"/>5.6.3. Standard Exceptions</span></h4><div class="calibre38">&#160;</div>
<p class="calibre14">The C++ library defines several classes that it uses to report problems encountered in the functions in the standard library. These exception classes are also intended to be used in the programs we write. These classes are defined in four headers:</p><div class="calibre15">&#160;</div>
<blockquote class="calibre26"><p class="calibre27">&#8226; The <code class="calibre23"><tt class="calibre23"><span class="calibre24">exception</span></tt></code> header defines the most general kind of exception class named <code class="calibre23"><tt class="calibre23"><span class="calibre24">exception</span></tt></code>. It communicates only that an exception occurred but provides no additional information.</p></blockquote><div class="calibre15">&#160;</div>
<blockquote class="calibre26"><p class="calibre27">&#8226; The <code class="calibre23"><tt class="calibre23"><span class="calibre24">stdexcept</span></tt></code> header defines several general-purpose exception classes, which are listed in <a href="059-5.6._try_blocks_and_exception_handling.html#filepos1392508">Table 5.1</a>.</p></blockquote><div class="calibre15">&#160;</div>
<p class="calibre51"><span class="calibre5"><a id="filepos1392508"/>Table 5.1. Standard Exception Classes Defined in <code class="calibre23"><tt class="calibre23"><span class="calibre24"><span><tt class="calibre23"><span class="calibre32"><span class="calibre5">&lt;stdexcept&gt;</span></span></tt></span></span></tt></code></span></p><div class="calibre12">&#160;</div>
<div class="calibre52"><img alt="Image" src="images/00038.jpg" class="calibre9"/></div><div class="calibre22">&#160;</div>
<blockquote class="calibre26"><p class="calibre27">&#8226; The <code class="calibre23"><tt class="calibre23"><span class="calibre24">new</span></tt></code> header defines the <code class="calibre23"><tt class="calibre23"><span class="calibre24">bad_alloc</span></tt></code> exception type, which we cover in &#167; <a href="114-12.1._dynamic_memory_and_smart_pointers.html#filepos2959483">12.1.2</a> (p. <a href="114-12.1._dynamic_memory_and_smart_pointers.html#filepos2959483">458</a>).</p></blockquote><div class="calibre15">&#160;</div>
<blockquote class="calibre26"><p class="calibre27">&#8226; The <code class="calibre23"><tt class="calibre23"><span class="calibre24">type_info</span></tt></code> header defines the <code class="calibre23"><tt class="calibre23"><span class="calibre24">bad_cast</span></tt></code> exception type, which we cover in &#167; <a href="178-19.2._runtime_type_identification.html#filepos5158705">19.2</a> (p. <a href="178-19.2._runtime_type_identification.html#filepos5158705">825</a>).</p></blockquote><div class="calibre15">&#160;</div>
<p class="calibre25">The library exception classes have only a few operations. We can create, copy, and assign objects of any of the exception types.</p><div class="calibre22">&#160;</div>
<p class="calibre25">We can only default initialize (&#167; <a href="022-2.2._variables.html#filepos350704">2.2.1</a>, p. <a href="022-2.2._variables.html#filepos350704">43</a>) <code class="calibre23"><tt class="calibre23"><span class="calibre24">exception</span></tt></code>, <code class="calibre23"><tt class="calibre23"><span class="calibre24">bad_alloc</span></tt></code>, and <code class="calibre23"><tt class="calibre23"><span class="calibre24">bad_cast</span></tt></code> objects; it is not possible to provide an initializer for objects of these exception types.</p><div class="calibre22">&#160;</div>
<p class="calibre25">The other exception types have the opposite behavior: We can initialize those objects from either a <code class="calibre23"><tt class="calibre23"><span class="calibre24">string</span></tt></code> or a C-style string, but we <em class="calibre16">cannot</em> default initialize them. When we create objects of any of these other exception types, we must supply an initializer. That initializer is used to provide additional information about the error that occurred.</p><div class="calibre22">&#160;</div>
<p class="calibre25">The exception types define only a single operation named <code class="calibre23"><tt class="calibre23"><span class="calibre24">what</span></tt></code>. That function takes no arguments and returns a <code class="calibre23"><tt class="calibre23"><span class="calibre24">const char*</span></tt></code> that points to a C-style character string (&#167; <a href="034-3.5._arrays.html#filepos918393">3.5.4</a>, p. <a href="034-3.5._arrays.html#filepos918393">122</a>). The purpose of this C-style character string is to provide some sort of textual description of the exception thrown.</p><div class="calibre22">&#160;</div>
<p class="calibre25"><a id="filepos1395337"/>The contents of the C-style string that <code class="calibre23"><tt class="calibre23"><span class="calibre24">what</span></tt></code> returns depends on the type of the exception object. For the types that take a string initializer, the <code class="calibre23"><tt class="calibre23"><span class="calibre24">what</span></tt></code> function returns that string. For the other types, the value of the string that <code class="calibre23"><tt class="calibre23"><span class="calibre24">what</span></tt></code> returns varies by compiler.</p><div class="calibre22">&#160;</div>
<div class="calibre42"><blockquote class="calibre26"><hr class="calibre34"/><blockquote class="calibre13"><p class="calibre43"><span class="calibre5">Exercises Section 5.6.3</span></p></blockquote><div class="calibre10">&#160;</div>
<blockquote class="calibre13"><p class="calibre44"><a/><strong class="calibre5">Exercise 5.23:</strong> Write a program that reads two integers from the standard input and prints the result of dividing the first number by the second.</p></blockquote><div class="calibre10">&#160;</div>
<blockquote class="calibre13"><p class="calibre44"><a/><strong class="calibre5">Exercise 5.24:</strong> Revise your program to throw an exception if the second number is zero. Test your program with a zero input to see what happens on your system if you don&#8217;t <code class="calibre23"><tt class="calibre23"><span class="calibre24">catch</span></tt></code> an exception.</p></blockquote><div class="calibre10">&#160;</div>
<blockquote class="calibre13"><p class="calibre44"><a/><strong class="calibre5">Exercise 5.25:</strong> Revise your program from the previous exercise to use a <code class="calibre23"><tt class="calibre23"><span class="calibre24">try</span></tt></code> block to <code class="calibre23"><tt class="calibre23"><span class="calibre24">catch</span></tt></code> the exception. The <code class="calibre23"><tt class="calibre23"><span class="calibre24">catch</span></tt></code> clause should print a message to the user and ask them to supply a new number and repeat the code inside the <code class="calibre23"><tt class="calibre23"><span class="calibre24">try</span></tt></code>.</p></blockquote><div class="calibre10">&#160;</div>
<hr class="calibre34"/></blockquote></div><div class="calibre3">&#160;</div>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr><td><div STYLE="MARGIN-LEFT: 0.15in;"><a href="001-contents.html"><img src="images/teamlib.gif" width="62" height="15" border="0" align="absmiddle"  alt="Team LiB"></a></div></td><td align="right"><div STYLE="MARGIN-LEFT: 0.15in;">
<a href="058-5.5._jump_statements.html"><img src="images/previous.gif" width="62" height="15" border="0" align="absmiddle" alt="Previous Section"></a>
<a href="060-chapter_summary.html"><img src="images/next.gif" width="41" height="15" border="0" align="absmiddle" alt="Next Section"></a></div></td></tr></table></body></html>
